server:
  port: 8080
spring:
  security:
    oauth2:
      client:
        provider: # Refs: https://docs.spring.io/spring-security/site/docs/current/reference/html5/#oauth2login-common-oauth2-provider
          azure-active-directory:
            issuer-uri: https://login.microsoftonline.com/3153a8d3-69c7-46e7-a417-b614f0cfa4fb/v2.0 # Refs: https://docs.spring.io/spring-security/site/docs/current/reference/html5/#webflux-oauth2-login-openid-provider-configuration
            user-name-attribute: name
        registration:
          cox:
            provider: azure-active-directory
            client-id: e1094794-9aad-4084-899e-cd4599baec96
            client-secret: jF.7Q~EHgsC3VQNkamxgaZYPUFRFa8AJ~KUR.
            scope: openid, profile # Refs: https://docs.microsoft.com/azure/active-directory/develop/v2-permissions-and-consent#openid-connect-scopes
            redirect-uri: http://18.116.66.218/login/oauth2/code/